name: 'terraform_state_artifact'
description: 'Sets up and runs Terraform, and creates an encrypted Terraform artifact'
author: 'Sturla Bragason'
inputs:
  encryptionkey:
    description: 'Used to read artifact and as a key to encrypt and decrypt the state file artifact'
    required: true
  apply:
    description: 'terraform apply'
    required: false
    default: true
  custom_plan_flags:
    description: 'Add custom flags to the terraform plan command'
    required: false
    default: ''
  custom_apply_flags:
    description: 'Add custom flags to the terraform apply command'
    required: false
    default: ''
  path:
    description: 'Terraform configuration path'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - id: terraform
      working-directory: ${{ inputs.path }}
      env:
        INPUTS_APPLY: ${{ inputs.apply }}
        INPUTS_CUSTOM_PLAN_FLAGS: ${{ inputs.custom_plan_flags }}
        INPUTS_CUSTOM_APPLY_FLAGS: ${{ inputs.custom_apply_flags }}
        REPO: ${{ github.repository }}
        TOKEN: ${{ github.token }}
        ENCRYPTIONKEY: ${{ inputs.encryptionkey }}
        PATH: ${{ inputs.path }}
        TWILIO_ACCOUNT_SID: ${{ env.TF_VAR_TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ env.TF_VAR_TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ env.TF_VAR_TWILIO_API_SECRET }}
        TF_WORKSPACE_SID: ${{ env.TF_WORKSPACE_SID }}
        TF_DEFAULT_WORKFLOW_SID: ${{ env.TF_DEFAULT_WORKFLOW_SID }}
        TF_DEFAULT_TASK_QUEUE_SID: ${{ env.TF_DEFAULT_TASK_QUEUE_SID }}
        TF_SALES_TASK_QUEUE_SID: ${{ env.TF_SALES_TASK_QUEUE_SID }}
        TF_SUPPORT_TASK_QUEUE_SID: ${{ env.TF_SUPPORT_TASK_QUEUE_SID }}
        TF_CHAT_TASK_CHANNEL_SID: ${{ env.TF_CHAT_TASK_CHANNEL_SID }}
        TF_VOICE_TASK_CHANNEL_SID: ${{ env.TF_VOICE_TASK_CHANNEL_SID }}
        TF_VOICE_FLOW_SID: ${{ env.TF_VOICE_FLOW_SID }}
        TF_MESSAGING_FLOW_SID: ${{ env.TF_MESSAGING_FLOW_SID }}
        TF_CHAT_FLOW_SID: ${{ env.TF_CHAT_FLOW_SID }}
      run: ../../script.ps1 
      shell: pwsh
    - uses: actions/upload-artifact@v2
      with:
        name: terraformstatefile
        path: ./terraform.tfstate.enc
branding:
  icon: 'cloud'
  color: 'gray-dark'
