name: 'terraform_state_artifact'
description: 'Sets up and runs Terraform, and creates an encrypted Terraform artifact'
author: 'Sturla Bragason'
inputs:
  encryptionkey:
    description: 'Used to read artifact and as a key to encrypt and decrypt the state file artifact'
    required: true
  apply:
    description: 'terraform apply'
    required: false
    default: true
  custom_plan_flags:
    description: 'Add custom flags to the terraform plan command'
    required: false
    default: ''
  custom_apply_flags:
    description: 'Add custom flags to the terraform apply command'
    required: false
    default: ''
  path:
    description: 'Terraform configuration path'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - id: terraform
      working-directory: ${{ inputs.path }}
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ github.token }}
        PATH: ${{ inputs.path }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID_DEV }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY_DEV }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET_DEV }}
      run: ../../script.ps1 
      shell: pwsh
    - uses: actions/upload-artifact@v2
      with:
        name: terraformstatefile
        path: ./terraform.tfstate.enc
branding:
  icon: 'cloud'
  color: 'gray-dark'
