name: 'Terraform DELETE State'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: 'Environment to use for deployment'

# Note your actions must have read and write workflow permissions enabled
jobs:
  delete-terraform-state:
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - id: delete_terraform_state
        run: |
          echo "running delete_terraform_state"
          echo "### Job summary" >> $env:GITHUB_STEP_SUMMARY
          echo " - Repo: ${{ github.repository }}"  >> $env:GITHUB_STEP_SUMMARY
          echo " - Environment: ${{ env.ENVIRONMENT }}"  >> $env:GITHUB_STEP_SUMMARY
          echo " - Artifact Name: terraformstatefile-${{ env.ENVIRONMENT }}"  >> $env:GITHUB_STEP_SUMMARY
          echo " --- "  >> $env:GITHUB_STEP_SUMMARY
          echo "### Job Results "  >> $env:GITHUB_STEP_SUMMARY

          $Repo = "${{ github.repository }}"
          $BaseUri = "https://api.github.com"
          $ArtifactUri = "$BaseUri/repos/$Repo/actions/artifacts"
          $Token = "${{ github.token }}" | ConvertTo-SecureString -AsPlainText
          $RestResponse = Invoke-RestMethod -Authentication Bearer -Uri $ArtifactUri -Token $Token | Select-Object -ExpandProperty artifacts
          if ($RestResponse){
            $StateHistory = $RestResponse | Sort-Object -Property created_at -Descending | where name -eq "terraformstatefile-${{ env.ENVIRONMENT }}"


            if($StateHistory) {
              echo $StateHistory

              echo " - Historic State Files Found: $StateHistory.Length"  >> $env:GITHUB_STEP_SUMMARY
            
              $StateHistory.ForEach({ Invoke-RestMethod -uri $_.url -Token $Token -Authentication bearer -Method DELETE})
            } else {
              echo " - Historic State Files Found: 0"  >> $env:GITHUB_STEP_SUMMARY
            }

          } else {
            echo ":warning: No artifacts found for repository"  >> $env:GITHUB_STEP_SUMMARY
          }
        shell: pwsh


