name: 'Terraform DELETE State'



on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: 'Environment to use for deployment'

jobs:

  delete-terraform-state:
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
      - id: download_state
        run: |

          echo "### Deleting Terraform State for ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          
          $Repo = "${{ github.repository }}"
          $BaseUri = "https://api.github.com"
          $ArtifactUri = "$BaseUri/repos/$Repo/actions/artifacts"
          $Token = "${{ github.token }}" | ConvertTo-SecureString -AsPlainText
          $RestResponse = Invoke-RestMethod -Authentication Bearer -Uri $ArtifactUri -Token $Token | Select-Object -ExpandProperty artifacts
          if ($RestResponse){
            Write-Host "Rest response: $RestResponse"
            $StateHistory = $RestResponse | Sort-Object -Property created_at -Descending | where name -eq "terraformstatefile-${{ env.ENVIRONMENT }}"
            
            $StateHistory.ForEach({ Invoke-RestMethod -uri $_.url -Token $Token -Authentication bearer -Method DELETE})

          }
        shell: pwsh


