name: lint_plugin_v2

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'plugin-flex-ts-template-v2/**'
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install packages
        working-directory: ./plugin-flex-ts-template-v2
        run: npm ci
      - name: Run eslint
        working-directory: ./plugin-flex-ts-template-v2
        run: npm run lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        working-directory: ./plugin-flex-ts-template-v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"