name: "Terraform DELETE State"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: "Environment to use for deployment"

# Note your actions must have read and write workflow permissions enabled
# this script is intended for development and troubleshooting purposes
#
# terraform is only concered with resources in the definition and in its
# state.
#
# if the resource definition defines something that already exists
# then it is expected to exist in the state.

jobs:
  delete-terraform-state:
    name: Delete Terraform
    environment: ${{ github.event.inputs.environment }}
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      TF_STATE_FILES: ".terraform.lock.hcl|terraform.tfstate"
      TF_VAR_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TF_VAR_TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TF_VAR_TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      ENVIRONMENT: ${{ inputs.environment }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Twilio CLI
        run: |
          npm install -g twilio-cli
          twilio plugins:install @twilio-labs/plugin-serverless

      - name: Pull Terraform State
        working-directory: ./infra-as-code/state
        id: pull-state
        run: |
          ./pull_state.sh

      - name: Load script variables
        working-directory: ./infra-as-code/state
        run: |
          ./load_tf_vars.sh

      - id: delete_terraform_state
        working-directory: ./infra-as-code/terraform/environments/default
        run: |
          terraform init
          terraform destroy -input=false -auto-approve
          twilio api:serverless:v1:services:remove --sid tfstate
