on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TWILIO_ACCOUNT_SID:
        required: true
      TWILIO_API_KEY:
        required: true
      TWILIO_API_SECRET:
        required: true
      TF_ENCRYPTION_KEY:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: "Environment to use for deployment"

jobs:
  terraform_deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: Deploy Terraform
    env:
      ENCRYPTION_KEY: ${{ secrets.TF_ENCRYPTION_KEY }}
      TF_STATE_FILES: ".terraform.lock.hcl|terraform.tfstate"
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      TF_VAR_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TF_VAR_TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TF_VAR_TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install Twilio CLI
        run: |
          npm install -g twilio-cli
          twilio plugins:install @twilio-labs/plugin-serverless

      - name: Pull Terraform State
        working-directory: ./infra-as-code/state
        id: pull-state
        run: |
          ./pull_state.sh

      - name: Detect serverless projects
        working-directory: ./infra-as-code/util
        run: |
          npm i
          npm run buildServiceManifest -- --servicesRoot=../../services
          echo "## Services" >> $GITHUB_STEP_SUMMARY
          echo "### Services Manifest" >> $GITHUB_STEP_SUMMARY 
          echo '```yaml' >> $GITHUB_STEP_SUMMARY
          cat ../../services/services-manifest.yaml >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "### :warning: Missing env vars" >> $GITHUB_STEP_SUMMARY
          grep missing ../../services/services-manifest.yaml >> $GITHUB_STEP_SUMMARY

      - name: Build serverless projects
        env:
          CI: false
        working-directory: ./services
        run: |
          SERVICE_FOLDERS=`ls -d */ | xargs -I{} echo $(pwd)/{}`
          for service_folder in $SERVICE_FOLDERS; do \
            if [ -d "$service_folder" ]; then
              echo "### :open_file_folder: $service_folder" >> $GITHUB_STEP_SUMMARY
              cd $service_folder
              yarn
              yarn build || echo "- :warning: No build script detected for $service_folder" >> $GITHUB_STEP_SUMMARY
            fi
          done

      - name: Load script variables
        working-directory: ./infra-as-code/state
        run: |
          ./load_tf_vars.sh

      - name: Import Internal State
        working-directory: ./infra-as-code/state
        run: |
          terraform -chdir="../terraform/environments/default" init -input=false
          echo "SKIP_TF_INIT=true" >> $GITHUB_ENV
          ./import_internal_state.sh
        if: env.TFSTATE_BUCKET == ''
        id: import_internal_state

      - name: Terraform plan & apply
        working-directory: ./infra-as-code/terraform/environments/default
        run: |
#          if [ $SKIP_TF_INIT != "true" ]; then
          terraform init -input=false
#          fi
          echo '### Terraform plan' >> $GITHUB_STEP_SUMMARY
          terraform plan -out tf.plan
          echo '```' >> $GITHUB_STEP_SUMMARY 
          terraform show -no-color tf.plan >> $GITHUB_STEP_SUMMARY 
          echo '```' >> $GITHUB_STEP_SUMMARY
          terraform apply -input=false -auto-approve tf.plan

      - name: Export State
        working-directory: ./infra-as-code/state
        if: always()
        run: |
          ./push_state.sh
#        if: steps.import_internal_state.outputs.JOB_FAILED == 'false'
