name: terraform_deploy_dev

on:
  # Run on merge to main
  #push:
  #  branches:
  #  - main

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:



#env:
  
  ## these environment variable names are required by the terraform provider
  #TF_VAR_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  #TF_VAR_TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
  #TF_VAR_TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

  # these environment variables names are required by twilio cli
  #TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  #TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
  #TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ENVIRONMENT: dev
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      TF_VAR_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TF_VAR_TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      TF_VAR_TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
    steps:
      - uses: actions/checkout@v1 
      - uses: ./.github/actions/terraform_state_artifact
        with:
          encryptionkey: ${{ secrets.TF_ENCRYPTION_KEY }}
          path: ./infra-as-code/terraform/environments/default
