name: terraform_deploy_dev

on:
  # Run on merge to main
  #push:
  #  branches:
  #  - main

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  ## these environment variable names are required by the terraform provider
  TF_VAR_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID_DEV }}
  TF_VAR_TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY_DEV }}
  TF_VAR_TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET_DEV }}

  # these environment variables names are required by twilio cli
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID_DEV }}
  TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY_DEV }}
  TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET_DEV }}

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - uses: ./.github/actions/terraform_state_artifact
        with:
          encryptionkey: ${{ secrets.TF_ENCRYPTION_KEY }}
          path: ./infra-as-code/terraform/environments/default
